version: '3.9'

# Вынести пароли в  .env

services:
  postgres_db:
    image: postgres:15.3-bullseye
    container_name: postgres_db
    restart: always
    env_file:
      - docker.env
    ports:
      - "5433:5433"
    # networks:
    #   - nest-init
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
      
  nestjs-api:
    image: nestjs-api
    container_name: nestjs-api
    env_file:
      - .env
    ports:
      - "7777:7777"
    # networks:
    #   - nest-init
    depends_on:
      - postgres_db


volumes:
    postgres_data:

# networks:
#   nest-init:
#     driver: bridge